import type { Metadata } from "next";
import Link from "next/link";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <nav>
          <Link href="/">Home</Link>
          <Link href="/enemies">Enemies</Link>
          <Link href="/weapons">Weapons</Link>
          <Link href="/armors">Armors</Link>
          <Link href="/items">Items</Link>
          <Link href="/gear-finder">Gear Finder</Link>
        </nav>
        <div className="main-wrapper">{children}</div>
      </body>
    </html>
  );
}
